export default {
  FETCH_START: 'FETCH_START',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_FAIL: 'FETCH_FAIL',
  SEARCH_AND_FETCH: 'SEARCH_AND_FETCH',
  GET_FULLSIZE_PHOTO: 'GET_FULLSIZE_PHOTO',
  DELETE_CLICKED_PHOTO: 'DELETE_CLICKED_PHOTO',
  ADD_TO_FAVOURITES: 'ADD_TO_FAVOURITES'
}